"""Options pricing, Greeks and implied volatility.

The public surface is deliberately small: a value object describing the option
and its market, and free functions over it.
"""

from .american import bjerksund_stensland, bjerksund_stensland_2002, trigger_price
from .barrier import (
    BARRIER_DIGITS,
    BarrierError,
    barrier_price,
    beyond_term,
    cannot_pay,
    is_structurally_worthless,
    is_touched,
    monitoring_shift,
    reflected_beyond_term,
    reflected_term,
    vanilla_term,
)
from .bivariate import norm_cdf2
from .bsm import (
    Inputs,
    OptionType,
    d1_d2,
    forward,
    intrinsic,
    log_moneyness,
    parity_gap,
    price,
)
from .greeks import (
    charm,
    colour,
    delta,
    dual_delta,
    dual_gamma,
    forward_delta,
    gamma,
    rho,
    rho_carry,
    speed,
    theta,
    vanna,
    vega,
    veta,
    volga,
    zomma,
)
from .heston import (
    Branch,
    Contract,
    Heston,
    SmilePoint,
    branch_discrepancy,
    char_func,
    gil_pelaez_price,
    lewis_price,
    smile,
)
from .heston_mc import (
    MartingaleCorrectionError,
    Scheme,
    conditional_mean,
    conditional_variance,
    variance_path,
)
from .implied import Bounds, Method, Quote, Solution, bounds, implied_vol, solve
from .lattice import (
    Exercise,
    Lattice,
    LatticePrice,
    boundary,
    min_steps,
    price_lattice,
    richardson,
)
from .monte_carlo import Barrier, Estimate, Settings, asian, barrier, european, geometric_asian
from .normal import norm_cdf, norm_pdf, norm_ppf
from .pde import (
    DupireLocalVol,
    FrontStub,
    LocalVolatility,
    LocalVolError,
    Mesh,
    MeshPrice,
    dupire_local_vol,
    price_pde,
)
from .quadrature import (
    QuadratureError,
    adaptive_quad,
    fixed_quad,
    gauss_legendre,
    semi_infinite_quad,
)

# ``sabr.calibrate``, ``sabr.density`` and ``sabr.smile`` are deliberately not
# re-exported here. ``svi`` already has a ``calibrate`` and a ``density`` and
# ``heston`` already has a ``smile``, and they are different functions rather
# than alternative spellings: SVI's density is in log-moneyness coordinates,
# SABR's is in the strike, and flattening them into one namespace would make
# whichever import came last silently win. They are reached as
# ``moneyness.sabr.calibrate`` and so on.
from .sabr import (
    Calibration,
    SabrParameters,
    Smile,
    bachelier,
    bachelier_vega,
    density_floor,
    implied_normal_vol,
    lognormal_volatility,
    normal_volatility,
    shifted_lognormal_volatility,
)
from .surface import Calendar, LocalVol, Surface
from .svi import SVI, Butterfly, Fit, calibrate, density, durrleman
from .variance import (
    BadStrip,
    Centring,
    Replication,
    Strip,
    VarianceSwap,
    VolatilitySwap,
    fair_variance,
    fair_variance_from_strip,
    integrated_variance_variance,
    truncation_error,
    volatility_swap_strike,
)

# Kept in step with the version in pyproject.toml by a test, because the two
# are written in different files and nothing else would notice them drifting.
__version__ = "0.1.0"

__all__ = [
    "BARRIER_DIGITS",
    "SVI",
    "BadStrip",
    "Barrier",
    "BarrierError",
    "Bounds",
    "Branch",
    "Butterfly",
    "Calendar",
    "Calibration",
    "Centring",
    "Contract",
    "DupireLocalVol",
    "Estimate",
    "Exercise",
    "Fit",
    "FrontStub",
    "Heston",
    "Inputs",
    "Lattice",
    "LatticePrice",
    "LocalVol",
    "LocalVolError",
    "LocalVolatility",
    "MartingaleCorrectionError",
    "Mesh",
    "MeshPrice",
    "Method",
    "OptionType",
    "QuadratureError",
    "Quote",
    "Replication",
    "SabrParameters",
    "Scheme",
    "Settings",
    "Smile",
    "SmilePoint",
    "Solution",
    "Strip",
    "Surface",
    "VarianceSwap",
    "VolatilitySwap",
    "__version__",
    "adaptive_quad",
    "asian",
    "bachelier",
    "bachelier_vega",
    "barrier",
    "barrier_price",
    "beyond_term",
    "bjerksund_stensland",
    "bjerksund_stensland_2002",
    "boundary",
    "bounds",
    "branch_discrepancy",
    "calibrate",
    "cannot_pay",
    "char_func",
    "charm",
    "colour",
    "conditional_mean",
    "conditional_variance",
    "d1_d2",
    "delta",
    "density",
    "density_floor",
    "dual_delta",
    "dual_gamma",
    "dupire_local_vol",
    "durrleman",
    "european",
    "fair_variance",
    "fair_variance_from_strip",
    "fixed_quad",
    "forward",
    "forward_delta",
    "gamma",
    "gauss_legendre",
    "geometric_asian",
    "gil_pelaez_price",
    "implied_normal_vol",
    "implied_vol",
    "integrated_variance_variance",
    "intrinsic",
    "is_structurally_worthless",
    "is_touched",
    "lewis_price",
    "log_moneyness",
    "lognormal_volatility",
    "min_steps",
    "monitoring_shift",
    "norm_cdf",
    "norm_cdf2",
    "norm_pdf",
    "norm_ppf",
    "normal_volatility",
    "parity_gap",
    "price",
    "price_lattice",
    "price_pde",
    "reflected_beyond_term",
    "reflected_term",
    "rho",
    "rho_carry",
    "richardson",
    "semi_infinite_quad",
    "shifted_lognormal_volatility",
    "smile",
    "solve",
    "speed",
    "theta",
    "trigger_price",
    "truncation_error",
    "vanilla_term",
    "vanna",
    "variance_path",
    "vega",
    "veta",
    "volatility_swap_strike",
    "volga",
    "zomma",
]
