"""Command-line access to the library.

Subcommands: ``price`` for a single option, ``greeks`` for its sensitivities,
``iv`` to invert a quoted price, ``ladder`` for a table of strikes at one
maturity, ``term`` for the transpose of it, ``surface`` to fit a surface to
quotes, ``american`` for a lattice valuation with the right to exercise
early, and ``heston`` for a smile generated by stochastic volatility rather
than fitted to quotes, and ``variance`` for the fair strike of a variance swap
replicated out of out-of-the-money prices.

The carry is specified in whichever way suits the instrument — ``--carry``
directly, ``--dividend`` for a share, ``--future`` for Black's model — rather
than making the caller do the arithmetic.
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from collections.abc import Callable, Iterable, Sequence
from pathlib import Path

from . import __version__
from .american import bjerksund_stensland, bjerksund_stensland_2002, trigger_price
from .asian import (
    average_moments,
    parity_difference,
    price_bounds,
    turnbull_wakeman,
)
from .barrier import barrier_price, is_structurally_worthless, monitoring_shift
from .bsm import Inputs, OptionType, forward, parity_gap, price
from .greeks import (
    charm,
    colour,
    delta,
    dual_delta,
    dual_gamma,
    gamma,
    rho,
    rho_carry,
    speed,
    theta,
    vanna,
    vega,
    veta,
    volga,
    zomma,
)
from .heston import Contract, Heston, gil_pelaez_price, lewis_price, smile
from .heston import price as heston_price
from .heston_mc import asian as heston_asian
from .heston_mc import barrier as heston_barrier
from .heston_mc import european as heston_european
from .implied import Method, Quote, black, bounds, implied_vol, solve
from .lattice import Exercise, Lattice, boundary, min_steps, price_lattice, richardson
from .monte_carlo import Barrier, Settings
from .pde import LocalVolError, Mesh, dupire_local_vol, price_pde
from .sabr import (
    SabrParameters,
    bachelier,
    density,
    density_floor,
    lognormal_volatility,
    normal_volatility,
)
from .spread import (
    AssetPair,
    SpreadError,
    accuracy_floor,
    exchange,
    kirk,
    spread_bounds,
    spread_price,
)
from .surface import Surface
from .svi import SVI, Butterfly, calibrate
from .variance import (
    BadStrip,
    Centring,
    Strip,
    fair_variance,
    fair_variance_from_strip,
    truncation_error,
    volatility_swap_strike,
)

__all__ = ["main"]


def _carry_from(args: argparse.Namespace) -> float | None:
    """Resolve the cost of carry from whichever flag was given."""
    given = [args.carry is not None, args.dividend is not None, args.future]
    if sum(given) > 1:
        raise SystemExit("give at most one of --carry, --dividend and --future")
    if args.future:
        return 0.0
    if args.dividend is not None:
        return float(args.rate) - float(args.dividend)
    return None if args.carry is None else float(args.carry)


def _add_market(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--spot", type=float, required=True, help="price of the underlying")
    parser.add_argument("--strike", type=float, required=True, help="exercise price")
    parser.add_argument("--time", type=float, required=True, help="year fraction to expiry")
    parser.add_argument("--rate", type=float, default=0.0, help="continuous discount rate")
    carry = parser.add_argument_group("cost of carry (at most one)")
    carry.add_argument("--carry", type=float, default=None, help="cost of carry directly")
    carry.add_argument("--dividend", type=float, default=None, help="continuous dividend yield")
    carry.add_argument(
        "--future", action="store_true", help="option on a future, so the carry is zero"
    )
    parser.add_argument("--put", action="store_true", help="price a put; the default is a call")


def _option_of(args: argparse.Namespace) -> OptionType:
    return OptionType.PUT if args.put else OptionType.CALL


def _inputs_of(args: argparse.Namespace) -> Inputs:
    return Inputs(args.spot, args.strike, args.time, args.rate, args.vol, carry=_carry_from(args))


def _run_price(args: argparse.Namespace) -> int:
    inputs = _inputs_of(args)
    option = _option_of(args)
    print(f"{option.value:>18}  {price(inputs, option):.10f}")
    print(f"{'forward':>18}  {forward(inputs):.10f}")
    print(f"{'discount factor':>18}  {inputs.discount:.10f}")
    print(f"{'parity residual':>18}  {parity_gap(inputs):.3e}")
    return 0


def _run_greeks(args: argparse.Namespace) -> int:
    inputs = _inputs_of(args)
    option = _option_of(args)
    rows: list[tuple[str, float]] = [
        ("price", price(inputs, option)),
        ("delta", delta(inputs, option)),
        ("gamma", gamma(inputs)),
        ("vega", vega(inputs)),
        ("theta", theta(inputs, option)),
        ("rho (rate)", rho(inputs, option)),
        ("rho (carry)", rho_carry(inputs, option)),
        ("vanna", vanna(inputs)),
        ("volga", volga(inputs)),
        ("charm", charm(inputs, option)),
        ("veta", veta(inputs)),
        ("colour", colour(inputs)),
        ("speed", speed(inputs)),
        ("zomma", zomma(inputs)),
        ("dual delta", dual_delta(inputs, option)),
        ("dual gamma", dual_gamma(inputs)),
    ]
    width = max(len(name) for name, _ in rows)
    for name, value in rows:
        print(f"{name:>{width}}  {value:>18.10f}")
    print()
    print("vega is per unit of volatility and theta is per year.")
    return 0


def _run_iv(args: argparse.Namespace) -> int:
    quote = Quote(args.spot, args.strike, args.time, args.rate, args.price, carry=_carry_from(args))
    option = _option_of(args)
    limits = bounds(quote, option)
    method = Method.BRENT if args.brent else Method.NEWTON
    try:
        solution = solve(quote, option, method)
    except ValueError as error:
        print(f"could not invert the quote: {error}", file=sys.stderr)
        print(
            f"the price must lie in [{limits.lower:.10f}, {limits.upper:.10f}]",
            file=sys.stderr,
        )
        return 1
    print(f"{'implied volatility':>20}  {solution.vol:.10f}")
    print(f"{'total volatility':>20}  {solution.total_vol:.10f}")
    print(f"{'method':>20}  {solution.method.value}")
    print(f"{'iterations':>20}  {solution.iterations}")
    print(f"{'price residual':>20}  {solution.residual:.3e}")
    print(f"{'arbitrage bounds':>20}  [{limits.lower:.10f}, {limits.upper:.10f}]")
    return 0


def _run_ladder(args: argparse.Namespace) -> int:
    carry = _carry_from(args)
    step = (args.high - args.low) / max(args.steps - 1, 1)
    header = f"{'strike':>10} {'call':>12} {'put':>12} {'delta':>10} {'gamma':>10} {'vega':>12}"
    print(header)
    print("-" * len(header))
    for index in range(args.steps):
        strike = args.low + index * step
        inputs = Inputs(args.spot, strike, args.time, args.rate, args.vol, carry=carry)
        print(
            f"{strike:>10.4f}"
            f" {price(inputs, OptionType.CALL):>12.6f}"
            f" {price(inputs, OptionType.PUT):>12.6f}"
            f" {delta(inputs, OptionType.CALL):>10.6f}"
            f" {gamma(inputs):>10.6f}"
            f" {vega(inputs):>12.6f}"
        )
    return 0


def _run_term(args: argparse.Namespace) -> int:
    """One strike across a range of maturities: the transpose of the ladder.

    The maturities are spaced geometrically rather than evenly. A term
    structure is read in ratios -- a week against a month against a year --
    and an even grid from one week to two years spends almost all of its rows
    on maturities that differ from each other by a rounding error while
    skipping the short end entirely, which is the part that moves.
    """
    carry = _carry_from(args)
    if args.near <= 0.0 or args.far <= 0.0:
        raise SystemExit("--near and --far must both be positive")
    if args.far < args.near:
        raise SystemExit("--far must not be before --near")
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")

    header = (
        f"{'maturity':>10} {'call':>12} {'put':>12} {'delta':>10}"
        f" {'gamma':>10} {'vega':>12} {'theta':>12}"
    )
    print(header)
    print("-" * len(header))

    ratio = 1.0 if args.steps == 1 else (args.far / args.near) ** (1.0 / (args.steps - 1))
    for index in range(args.steps):
        time = args.near * ratio**index
        inputs = Inputs(args.spot, args.strike, time, args.rate, args.vol, carry=carry)
        print(
            f"{time:>10.4f}"
            f" {price(inputs, OptionType.CALL):>12.6f}"
            f" {price(inputs, OptionType.PUT):>12.6f}"
            f" {delta(inputs, OptionType.CALL):>10.6f}"
            f" {gamma(inputs):>10.6f}"
            f" {vega(inputs):>12.6f}"
            f" {theta(inputs, OptionType.CALL):>12.6f}"
        )
    return 0


def _read_quotes(source: str) -> dict[float, list[tuple[float, float]]]:
    """Read ``maturity,strike,vol`` rows, grouped by maturity.

    A header row is optional and detected by trying to parse it as numbers,
    which is more forgiving than demanding a particular spelling and less
    fragile than guessing from the text. It is allowed to follow comment lines
    rather than having to be the very first line, since a file that explains
    where its quotes came from is more useful than one that does not.

    Args:
        source: Path to a CSV, or ``-`` for standard input.

    Returns:
        Quotes grouped by maturity, in file order within each group.

    Raises:
        SystemExit: If the file cannot be read, a row is malformed, or a value
            is outside its domain. The row number is always reported, because a
            surface is typically a few hundred rows and "one of them is wrong"
            is not a usable diagnostic.
    """
    if source == "-":
        lines: Iterable[str] = sys.stdin.read().splitlines()
    else:
        path = Path(source)
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError as error:
            raise SystemExit(f"cannot read {source}: {error}") from error

    grouped: dict[float, list[tuple[float, float]]] = {}
    for number, row in enumerate(csv.reader(lines), start=1):
        cleaned = [field.strip() for field in row if field.strip()]
        if not cleaned or cleaned[0].startswith("#"):
            continue
        if len(cleaned) < 3:
            raise SystemExit(
                f"row {number}: expected maturity, strike and vol, got {len(cleaned)} fields"
            )
        try:
            maturity, strike, vol = (float(field) for field in cleaned[:3])
        except ValueError:
            if not grouped:
                continue  # a header, wherever it happens to sit
            raise SystemExit(f"row {number}: {cleaned[:3]} are not three numbers") from None
        if maturity <= 0.0:
            raise SystemExit(f"row {number}: maturity {maturity} is not positive")
        if strike <= 0.0:
            raise SystemExit(f"row {number}: strike {strike} is not positive")
        if vol <= 0.0:
            raise SystemExit(f"row {number}: volatility {vol} is not positive")
        grouped.setdefault(maturity, []).append((strike, vol))

    if not grouped:
        raise SystemExit(f"no quotes found in {source}")
    return grouped


def _run_surface(args: argparse.Namespace) -> int:
    """Fit a surface to quoted volatilities and report what it implies.

    Returns 1 when the fitted surface admits arbitrage, so that the command is
    usable as a check in a pipeline. That is a finding about the data rather
    than a failure of the request, which is why it is an exit status and not an
    exception.
    """
    grouped = _read_quotes(args.quotes)
    carry = args.rate if args.carry is None else args.carry

    fitted: list[tuple[float, SVI]] = []
    print(
        f"{'maturity':>9} {'quotes':>7} {'rmse':>11} {'max err':>11}"
        f" {'a':>9} {'b':>8} {'rho':>8} {'m':>8} {'s':>8}"
        f" {'left':>7} {'right':>7} {'worst g':>10}"
    )
    print("-" * 120)

    arbitrage = False
    for maturity in sorted(grouped):
        quotes = grouped[maturity]
        if len(quotes) < 5:
            raise SystemExit(
                f"maturity {maturity} has {len(quotes)} quotes; "
                "a five-parameter slice needs at least five"
            )
        forward_price = args.spot * math.exp(carry * maturity)
        log_moneyness = [math.log(strike / forward_price) for strike, _ in quotes]
        variance = [vol * vol * maturity for _, vol in quotes]

        try:
            fit = calibrate(log_moneyness, variance)
        except ValueError as error:
            raise SystemExit(f"maturity {maturity}: {error}") from error

        slice_ = fit.slice_
        left, right = slice_.wing_slopes
        report = Butterfly.scan(slice_)
        if not report.free:
            arbitrage = True
        print(
            f"{maturity:>9.4f} {len(quotes):>7d} {fit.rmse:>11.3e} {fit.max_error:>11.3e}"
            f" {slice_.a:>9.5f} {slice_.b:>8.5f} {slice_.rho:>8.5f}"
            f" {slice_.m:>8.5f} {slice_.s:>8.5f}"
            f" {left:>7.3f} {right:>7.3f} {report.worst:>10.5f}"
        )
        fitted.append((maturity, slice_))

    surface = Surface(fitted)

    print()
    print("butterfly (worst value of Durrleman's function; negative implies a negative density)")
    for maturity, worst, at in surface.butterfly():
        quoted = "quoted" if maturity in grouped else "interpolated"
        flag = "  ARBITRAGE" if worst < 0.0 else ""
        if worst < 0.0:
            arbitrage = True
        print(f"  T={maturity:<9.4f} {quoted:<13} g={worst:>10.5f} at k={at:>7.3f}{flag}")

    print()
    if len(fitted) < 2:
        print("calendar: a single maturity cannot cross another")
    else:
        print("calendar (total variance must not fall as maturity grows)")
        for entry in surface.calendar():
            if entry.free:
                margin = -entry.worst
                print(
                    f"  {entry.earlier:.4f} -> {entry.later:.4f}  clear,"
                    f" closest approach {margin:.5f}"
                )
            else:
                arbitrage = True
                print(
                    f"  {entry.earlier:.4f} -> {entry.later:.4f}  CROSSES by"
                    f" {entry.worst:.5f} at k={entry.at:.3f}"
                )

    if args.local_vol:
        print()
        print("local volatility by the Dupire identity")
        maturities = surface.maturities
        if len(maturities) < 2:
            print("  a single maturity gives no slope in maturity, so dw/dT is zero")
            print("  everywhere and the identity has nothing to report")
            print()
            if arbitrage:
                print("verdict: the fitted surface admits arbitrage")
                return 1
            print("verdict: no arbitrage found")
            return 0

        # Strictly inside the quoted range. At a quoted endpoint the surface is
        # flat in maturity by construction -- that is what the extrapolation
        # rule says -- so dw/dT is zero there and the identity returns a local
        # volatility of zero. That number is a property of the extrapolation,
        # not of the market, and printing it in a column headed by a real
        # maturity would invite it to be read as one.
        near, far = maturities[0], maturities[-1]
        columns = 5
        times = [near + (far - near) * (i + 1) / (columns + 1) for i in range(columns)]
        header = f"{'k':>8}" + "".join(f"{t:>12.4f}" for t in times)
        print(header)
        print("-" * len(header))
        for step in range(-4, 5):
            k = step * 0.1
            cells = []
            for time in times:
                result = surface.local_vol(k, time)
                cells.append(f"{result.volatility:>12.6f}" if result.admissible else f"{'--':>12}")
            print(f"{k:>8.2f}" + "".join(cells))

    if args.reprice:
        print()
        _reprice(surface, grouped, args.spot, args.rate, carry)

    print()
    if arbitrage:
        print("verdict: the fitted surface admits arbitrage")
        return 1
    print("verdict: no arbitrage found")
    return 0


def _reprice(
    surface: Surface,
    grouped: dict[float, list[tuple[float, float]]],
    spot: float,
    rate: float,
    carry: float,
) -> None:
    """Solve every quote back out of the surface's own local volatility.

    This is the end-to-end check on the fit, and it is a different question
    from the two arbitrage conditions above. Those ask whether a local
    volatility exists; this asks whether the one that does reproduces the
    prices it was derived from. A surface can pass both conditions and still
    be repriced badly, because the fit per slice is a least squares and the
    quotes are not on it.

    The grid is deliberately modest. The residuals here are dominated by the
    slice fit rather than by the solve, and a finer mesh would spend time
    resolving the wrong term.
    """
    local = dupire_local_vol(surface, spot, carry=carry)
    mesh = Mesh(space_steps=300, time_steps=150)
    header = (
        f"repriced through the local volatility (quoted vol, recovered vol, gap)\n"
        f"{'maturity':>9} {'strike':>10} {'quoted':>10} {'recovered':>10} {'gap':>11}"
    )
    print(header)
    print("-" * 54)
    worst = 0.0
    for maturity in sorted(grouped):
        forward_price = spot * math.exp(carry * maturity)
        for strike, quoted in grouped[maturity]:
            option = OptionType.CALL if strike >= forward_price else OptionType.PUT
            try:
                solved = price_pde(
                    spot=spot,
                    strike=strike,
                    time=maturity,
                    rate=rate,
                    vol=local,
                    option=option,
                    carry=carry,
                    mesh=mesh,
                    breakpoints=local.breakpoints,
                )
                recovered = implied_vol(
                    Quote(
                        spot=spot,
                        strike=strike,
                        time=maturity,
                        rate=rate,
                        price=solved.value,
                        carry=carry,
                    ),
                    option,
                )
            except (LocalVolError, ValueError) as error:
                print(
                    f"{maturity:>9.4f} {strike:>10.4f} {quoted:>10.6f}"
                    f" {'--':>10}  {str(error)[:40]}"
                )
                continue
            gap = recovered - quoted
            worst = max(worst, abs(gap))
            print(
                f"{maturity:>9.4f} {strike:>10.4f} {quoted:>10.6f} {recovered:>10.6f} {gap:>+11.2e}"
            )
    print(f"worst gap in volatility: {worst:.3e}")


def _format_trigger(level: float) -> str:
    """An unreachable boundary is reported as such rather than as a number."""
    return "never reached" if math.isinf(level) else f"{level:.10f}"


def _run_american(args: argparse.Namespace) -> int:
    inputs = _inputs_of(args)
    option = _option_of(args)
    lattice = Lattice(args.lattice)

    floor = min_steps(inputs, lattice)
    if args.steps < floor:
        print(
            f"error: {args.steps} layers is below the {floor} this lattice needs "
            f"for the drift to stay inside the spread",
            file=sys.stderr,
        )
        return 1

    american = price_lattice(inputs, option, steps=args.steps, lattice=lattice, smooth=not args.raw)
    european = price_lattice(
        inputs,
        option,
        steps=args.steps,
        lattice=lattice,
        exercise=Exercise.EUROPEAN,
        smooth=not args.raw,
    )
    extrapolated = richardson(
        inputs, option, steps=args.steps, lattice=lattice, smooth=not args.raw
    )

    rows: list[tuple[str, str]] = [
        ("lattice", lattice.value),
        ("layers", str(args.steps)),
        ("smoothing", "off" if args.raw else "on"),
        ("american", f"{american.value:.10f}"),
        ("european (lattice)", f"{european.value:.10f}"),
        ("european (closed form)", f"{price(inputs, option):.10f}"),
        ("early exercise premium", f"{american.early_exercise_premium:.10f}"),
        ("american (extrapolated)", f"{extrapolated:.10f}"),
        ("bjerksund-stensland 1993", f"{bjerksund_stensland(inputs, option):.10f}"),
        ("bjerksund-stensland 2002", f"{bjerksund_stensland_2002(inputs, option):.10f}"),
        ("bs trigger price", _format_trigger(trigger_price(inputs, option))),
    ]
    width = max(len(name) for name, _ in rows)
    for name, value in rows:
        print(f"{name:>{width}}  {value}")

    if args.boundary:
        curve = boundary(inputs, option, steps=args.steps, lattice=lattice)
        print()
        if len(curve) <= 1:
            print("the exercise region is empty: early exercise is never optimal here.")
            return 0
        print(f"{'time':>10} {'critical spot':>16}")
        print("-" * 27)
        shown = curve[:: max(len(curve) // args.boundary_rows, 1)]
        if shown[-1] != curve[-1]:
            shown.append(curve[-1])
        for when, critical in shown:
            print(f"{when:>10.6f} {critical:>16.6f}")
    return 0


def _run_sabr(args: argparse.Namespace) -> int:
    """A SABR ladder, both volatility conventions, and the density.

    The two volatility columns are not conversions of one another: they are
    separate second-order expansions in the same small parameter, so the prices
    they imply differ by the expansion's own error -- which the price columns
    make visible rather than hiding behind a single number.
    """
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")
    if args.high < args.low:
        raise SystemExit("--high must not be below --low")
    try:
        parameters = SabrParameters(alpha=args.alpha, beta=args.beta, rho=args.rho, nu=args.nu)
    except ValueError as bad:
        raise SystemExit(str(bad)) from bad

    shift = args.shift
    fwd = args.forward + shift if shift is not None else args.forward
    if fwd <= 0.0:
        raise SystemExit(
            f"the forward is {fwd}, which the lognormal formula has no value "
            "at; pass --shift to displace it"
        )
    root = math.sqrt(args.time)
    step = (args.high - args.low) / max(args.steps - 1, 1)
    strikes = [args.low + index * step for index in range(args.steps)]

    at_the_money = normal_volatility(parameters, fwd, fwd, args.time) * root
    print(f"forward            {fwd:.6f}" + (f" (shifted by {shift})" if shift else ""))
    print(f"at-the-money sd    {at_the_money:.8f}")
    print(f"backbone exponent  {parameters.beta}")
    if parameters.is_lognormal:
        print("this is Black exactly: no vol of vol and a unit exponent")
    if parameters.is_normal:
        print("this is Bachelier exactly: no vol of vol and a zero exponent")
    print()
    header = (
        f"{'strike':>10} {'lognormal':>12} {'normal':>12} {'black':>14} "
        f"{'bachelier':>14} {'density':>12}"
    )
    print(header)
    print("-" * len(header))
    for strike in strikes:
        shifted = strike + shift if shift is not None else strike
        if shifted <= 0.0:
            print(f"{strike:>10.6f}   (strike not positive after the shift)")
            continue
        lognormal = lognormal_volatility(parameters, fwd, shifted, args.time)
        normal = normal_volatility(parameters, fwd, shifted, args.time)
        option = OptionType.PUT if shifted < fwd else OptionType.CALL
        from_black = black(fwd, shifted, lognormal * root, option)
        from_normal = bachelier(fwd, shifted, normal * root, option)
        here = density(parameters, fwd, shifted, args.time)
        print(
            f"{strike:>10.6f} {lognormal:>12.6%} {normal:>12.8f} "
            f"{from_black:>14.10f} {from_normal:>14.10f} {here:>12.4f}"
        )
    if args.floor:
        print()
        found = density_floor(parameters, fwd, args.time, lower=1e-4 * fwd)
        if found is None:
            print(
                "the density stays non-negative down to 1e-04 of the forward, which "
                "is a search that found nothing rather than a certificate"
            )
        else:
            deviations = (fwd - found) / at_the_money
            inside = density(parameters, fwd, 0.9 * found, args.time, step=1e-4 * found)
            print(
                f"the density turns negative below {found:.6f}, which is "
                f"{deviations:.2f} at-the-money standard deviations below the "
                f"forward; ten per cent further down it is {inside:.4f}"
            )
            print(
                "the value at the boundary itself is a bisected zero and is "
                "rounding, so the magnitude is read inside the region"
            )
    return 0


def _run_heston(args: argparse.Namespace) -> int:
    """A strike ladder under stochastic volatility, read back as a smile.

    The implied volatility column is the point of the command. Prices under a
    model with random variance are not comparable across strikes by eye;
    the volatilities that reproduce them are, and the shape they trace is the
    thing the parameters were chosen for.
    """
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")
    if args.low <= 0.0 or args.high < args.low:
        raise SystemExit("--low must be positive and --high must not be below it")

    model = Heston(args.v0, args.kappa, args.theta, args.sigma, args.rho)
    contract = Contract(args.spot, args.spot, args.time, args.rate, carry=_carry_from(args))
    step = (args.high - args.low) / max(args.steps - 1, 1)
    strikes = [args.low + index * step for index in range(args.steps)]

    feller = "holds" if model.satisfies_feller else "fails"
    print(f"forward           {contract.forward:.6f}")
    print(f"expected variance {model.expected_integrated_variance(args.time):.8f}")
    print(f"equivalent vol    {model.equivalent_vol(args.time):.6%}")
    print(f"Feller condition  {feller} (2 kappa theta - sigma^2 = {model.feller:+.6f})")
    print()

    header = f"{'strike':>10} {'side':>5} {'price':>14} {'implied vol':>13} {'log-moneyness':>15}"
    print(header)
    print("-" * len(header))
    for point in smile(model, contract, strikes):
        vol = "-" if point.implied_vol is None else f"{point.implied_vol:>12.6%}"
        print(
            f"{point.strike:>10.4f}"
            f" {point.option.value:>5}"
            f" {point.price:>14.8f}"
            f" {vol:>13}"
            f" {math.log(point.strike / contract.forward):>15.6f}"
        )

    if args.check:
        # The second route, for a caller who wants the agreement in front of
        # them rather than in the test suite.
        worst = 0.0
        for strike in strikes:
            one = Contract(args.spot, strike, args.time, args.rate, carry=_carry_from(args))
            option = OptionType.CALL if strike >= contract.forward else OptionType.PUT
            gap = lewis_price(model, one, option) - gil_pelaez_price(model, one, option)
            worst = max(worst, abs(gap))
        print()
        print(f"largest gap between the Lewis and Gil-Pelaez routes: {worst:.3e}")
    return 0


def _run_barrier(args: argparse.Namespace) -> int:
    """A barrier option, and the two things about it that surprise people.

    The volatility ladder is the point of the report. Every other price in this
    package rises with volatility; a knock-out whose barrier is near the spot
    does not, and the ladder shows it turning over rather than asserting that
    it does. The monitoring table is the other: the shift that represents a
    daily close is under a per cent of the barrier and is worth more than ten
    per cent of the price, because the price is levered about eighteen times to
    the level.
    """
    inputs = _inputs_of(args)
    option = _option_of(args)
    style = Barrier(args.barrier)
    if args.level <= 0.0:
        raise SystemExit("--level must be positive")

    continuous = barrier_price(inputs, option, args.level, style)
    vanilla = price(inputs, option)
    mirror = {
        Barrier.DOWN_AND_OUT: Barrier.DOWN_AND_IN,
        Barrier.DOWN_AND_IN: Barrier.DOWN_AND_OUT,
        Barrier.UP_AND_OUT: Barrier.UP_AND_IN,
        Barrier.UP_AND_IN: Barrier.UP_AND_OUT,
    }[style]
    other = barrier_price(inputs, option, args.level, mirror)

    print(f"{'contract':>18}  {style.value} {option.value} at {args.level:g}")
    print(f"{'vanilla':>18}  {vanilla:.10f}")
    print(f"{'this half':>18}  {continuous:.10f}")
    print(f"{mirror.value:>18}  {other:.10f}")
    print(f"{'parity residual':>18}  {continuous + other - vanilla:+.3e}")
    if is_structurally_worthless(inputs.strike, args.level, style, option):
        print(
            f"{'note':>18}  worth exactly nothing: finishing in the money "
            "requires breaching the barrier"
        )

    print()
    print("  volatility        price      vanilla")
    previous = None
    turned = False
    for vol in args.vols:
        moved = Inputs(args.spot, args.strike, args.time, args.rate, vol, carry=_carry_from(args))
        here = barrier_price(moved, option, args.level, style)
        if previous is not None and here < previous:
            turned = True
        print(f"  {vol:>10.4f}  {here:>11.6f}  {price(moved, option):>11.6f}")
        previous = here
    if turned and style.is_knock_out:
        print(
            "  the price turns over: the volatility that pays for the "
            "optionality also pays for the knock-out, so vega changes sign and "
            "no implied volatility can be read back"
        )

    if args.monitorings:
        print()
        print("  per year        level        price   over continuous")
        for frequency in args.monitorings:
            if frequency <= 0.0:
                raise SystemExit("--monitorings must be positive")
            level = monitoring_shift(args.level, style, args.vol, frequency)
            value = barrier_price(inputs, option, level, style)
            share = value / continuous - 1.0 if continuous != 0.0 else float("nan")
            print(f"  {frequency:>8.0f}  {level:>11.6f}  {value:>11.6f}  {share:>+15.2%}")
        print(
            "  the correction is first order in sqrt(dt): measured against "
            "simulation it is -0.33% off daily, +0.92% weekly and +6.82% "
            "monthly, so simulate a monthly contract rather than quoting this"
        )
    return 0


def _run_spread(args: argparse.Namespace) -> int:
    """An option on the difference of two assets, with its rigorous interval.

    Like the Asian command this leads with bounds rather than with a price,
    and for the same reason: the difference of two lognormals has no closed
    form, so an approximation on its own cannot be checked. Unlike the Asian
    case the interval here carries extra information -- the upper bound holds
    for every coupling of the two marginals, so how far it sits above the
    price is a reading of how far this correlation is from the worst one.

    Kirk's approximation is printed last and flagged when it leaves the
    interval, which it does at positive correlation and short strikes, and
    again at correlations near -1 and far strikes.
    """
    pair = AssetPair(
        args.forward1,
        args.forward2,
        args.time,
        args.rate,
        args.vol1,
        args.vol2,
        args.rho,
    )
    call = args.option == "call"
    strike = args.strike

    try:
        exact = spread_price(pair, strike, call=call)
    except SpreadError as error:
        print(f"cannot price: {error}", file=sys.stderr)
        return 1
    bounds = spread_bounds(pair, strike, call=call)

    print(f"{'contract':>22}  {args.option} on S1 - S2 struck at {strike:g}")
    print(f"{'forward spread':>22}  {pair.forward1 - pair.forward2:.10f}")
    print(f"{'spread vol':>22}  {pair.spread_total / math.sqrt(pair.time):.10f}")
    print()
    print(f"{'price':>22}  {exact:.10f}")
    print(f"{'resolves to':>22}  {accuracy_floor(pair, strike, call=call):.3e}  (absolute)")
    print()
    print(f"{'lower (half-space)':>22}  {bounds.lower:.10f}")
    print(f"{'upper (vanillas)':>22}  {bounds.upper:.10f}")
    print(f"{'interval width':>22}  {bounds.width:.10f}")
    if exact > 0.0:
        print(f"{'':>22}  {bounds.width / exact:.4f} of the price")
    print()
    if strike >= 0.0:
        print(f"{'exchange (K=0)':>22}  {exchange(pair):.10f}  (exact, Margrabe)")
    try:
        approximate = kirk(pair, strike, call=call)
    except SpreadError as error:
        print(f"{'Kirk':>22}  unavailable: {error}")
        return 0
    print(f"{'Kirk':>22}  {approximate:.10f}")
    if exact > 0.0:
        print(f"{'':>22}  {(approximate - exact) / exact:+.3e} relative")
    if not bounds.contains(approximate, slack=1e-12):
        low = approximate < bounds.lower
        side = "below the lower" if low else "above the upper"
        miss = bounds.lower - approximate if low else approximate - bounds.upper
        print(f"{'':>22}  outside the bounds, {side} bound by {miss:.3e}")
    return 0


def _run_asian(args: argparse.Namespace) -> int:
    """An average-price option, with the interval its price is known to lie in.

    The report leads with the bounds rather than with a price, because that is
    what distinguishes this instrument from the rest of the package: there is no
    closed form, so what can be stated is an interval and a bound inside it.

    The moment-matched price is shown last and flagged when it leaves that
    interval, which it does out of the money at moderate volatility. That is the
    whole reason the bounds are computed: moment matching is what most systems
    use and nothing but a rigorous bound can tell you when it has gone wrong.
    """
    inputs = _inputs_of(args)
    option = _option_of(args)
    steps = args.fixings

    moments = average_moments(inputs, steps)
    bounds = price_bounds(inputs, option, steps)
    matched = turnbull_wakeman(inputs, option, steps)
    vanilla = price(inputs, option)
    terminal = inputs.vol * inputs.vol * inputs.time

    print(f"{'contract':>22}  {option.value} on the average of {steps} fixings")
    print(f"{'average forward':>22}  {moments.first:.10f}")
    print(f"{'effective vol':>22}  {math.sqrt(moments.log_variance / inputs.time):.10f}")
    print(f"{'variance kept':>22}  {moments.log_variance / terminal:.6f}  of the terminal price's")
    print()
    print(f"{'lower (Curran)':>22}  {bounds.lower:.10f}")
    print(f"{'upper':>22}  {bounds.upper:.10f}")
    print(f"{'interval width':>22}  {bounds.width:.10f}")
    print(
        f"{'geometric':>22}  {bounds.geometric:.10f}"
        f"  ({'below' if option is OptionType.CALL else 'above'} by AM-GM)"
    )
    print()
    print(f"{'moment matched':>22}  {matched:.10f}")
    if not bounds.brackets(matched, tolerance=1e-12):
        low = matched < bounds.lower
        side = "below the lower" if low else "above the upper"
        miss = bounds.lower - matched if low else matched - bounds.upper
        print(f"{'':>22}  outside the bounds, {side} bound by {miss:.3e}")
    print(f"{'vanilla':>22}  {vanilla:.10f}")
    print(f"{'call - put':>22}  {parity_difference(inputs, steps):.10f}  (exact)")

    if args.fixing_table:
        print()
        print(f"{'fixings':>10}{'lower':>16}{'upper':>16}{'width':>14}{'matched':>16}")
        for count in (1, 2, 4, 12, 52, 252):
            table = price_bounds(inputs, option, count)
            print(
                f"{count:>10}{table.lower:>16.10f}{table.upper:>16.10f}"
                f"{table.width:>14.10f}{turnbull_wakeman(inputs, option, count):>16.10f}"
            )
    return 0


def _run_heston_path(args: argparse.Namespace) -> int:
    """A payoff the transform cannot reach, simulated under stochastic volatility.

    The European case is included on purpose even though the transform prices
    it exactly: it is the only payoff here with a known answer, so it is the
    one that says whether the simulation is working before the other two are
    believed.
    """
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")
    model = Heston(args.v0, args.kappa, args.theta, args.sigma, args.rho)
    contract = Contract(args.spot, args.strike, args.time, args.rate, carry=_carry_from(args))
    option = _option_of(args)
    settings = Settings(paths=args.paths, seed=args.seed, antithetic=True, control=True)

    if args.payoff == "european":
        estimate = heston_european(
            model, contract, option, args.steps, settings, not args.no_martingale
        )
    elif args.payoff == "asian":
        estimate = heston_asian(
            model, contract, option, args.steps, settings, not args.no_martingale
        )
    else:
        if args.level is None:
            raise SystemExit("--level is required for a barrier payoff")
        estimate = heston_barrier(
            model,
            contract,
            option,
            Barrier(args.barrier),
            args.level,
            args.steps,
            settings,
            not args.no_martingale,
            not args.no_bridge,
        )

    low, high = estimate.interval(0.95)
    print(f"payoff            {args.payoff} {option.value}")
    print(f"forward           {contract.forward:.6f}")
    print(f"Feller condition  {'holds' if model.satisfies_feller else 'fails'}")
    print(f"paths             {estimate.paths} in {estimate.samples} samples")
    print(f"steps             {args.steps}")
    print(f"control           {estimate.control or 'none'}")
    print(f"value             {estimate.value:.6f}")
    print(f"standard error    {estimate.standard_error:.6f}")
    print(f"95% interval      [{low:.6f}, {high:.6f}]")
    if args.payoff == "european":
        exact = heston_price(model, contract, option)
        deviations = (estimate.value - exact) / estimate.standard_error
        print(f"transform price   {exact:.6f}")
        gap = estimate.value - exact
        print(f"gap               {gap:+.6f} ({deviations:+.2f} standard errors)")
    return 0


def _read_price_quotes(source: str) -> list[tuple[float, float]]:
    """Read ``strike,price`` rows of out-of-the-money option prices.

    A header row is optional and detected by failing to parse as numbers, the
    same way the surface reader does it.

    Args:
        source: Path to a CSV, or ``-`` for standard input.

    Returns:
        The quotes in file order.

    Raises:
        SystemExit: If the file cannot be read or a row is malformed.
    """
    if source == "-":
        lines: Iterable[str] = sys.stdin.read().splitlines()
    else:
        path = Path(source)
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError as error:
            raise SystemExit(f"cannot read {source}: {error}") from error

    quotes: list[tuple[float, float]] = []
    for number, row in enumerate(csv.reader(lines), start=1):
        cleaned = [field.strip() for field in row if field.strip()]
        if not cleaned or cleaned[0].startswith("#"):
            continue
        if len(cleaned) < 2:
            raise SystemExit(f"row {number}: expected strike and price, got {len(cleaned)} fields")
        try:
            strike, value = (float(field) for field in cleaned[:2])
        except ValueError:
            if not quotes:
                continue  # a header, wherever it happens to sit
            raise SystemExit(f"row {number}: {cleaned[:2]} are not two numbers") from None
        if strike <= 0.0:
            raise SystemExit(f"row {number}: strike {strike} is not positive")
        if value < 0.0:
            raise SystemExit(f"row {number}: price {value} is negative")
        quotes.append((strike, value))

    if not quotes:
        raise SystemExit(f"no quotes found in {source}")
    return quotes


def _lattice_quotes(
    priced: Callable[[float, OptionType], float],
    forward: float,
    step: float,
    low: float,
    high: float,
) -> list[tuple[float, float]]:
    """Out-of-the-money prices on a lattice of strikes a multiple of ``step``.

    The lattice is a multiple of the step and takes no notice of the forward,
    which is the realistic case and the one the centring term exists for. At
    the split strike itself both options are at the money and neither is the
    out-of-the-money one, so the quote is their average, as the convention
    requires.
    """
    strikes: list[float] = []
    strike = step * math.ceil(forward * low / step)
    while strike <= forward * high:
        strikes.append(strike)
        strike += step
    inside = [k for k in strikes if k <= forward]
    if not inside:
        raise SystemExit("no lattice strike lies at or below the forward")
    reference = max(inside)
    quotes: list[tuple[float, float]] = []
    for strike in strikes:
        if strike < reference:
            quotes.append((strike, priced(strike, OptionType.PUT)))
        elif strike > reference:
            quotes.append((strike, priced(strike, OptionType.CALL)))
        else:
            both = priced(strike, OptionType.PUT) + priced(strike, OptionType.CALL)
            quotes.append((strike, 0.5 * both))
    return quotes


def _run_variance(args: argparse.Namespace) -> int:
    """The fair strike of a variance swap, by static replication of the smile.

    Three sources of prices, because the three answer different questions. A
    flat volatility is the case with an exact answer known in advance, so it
    says whether the replication is working at all. A Heston model also has an
    exact answer, in closed form and arrived at from an entirely different
    direction, so it says whether the replication is working on a smile rather
    than on a flat line. A file of quotes is the case anyone actually has, and
    for it the only honest diagnostics are the outer-tenth share and the
    log-moneyness the strikes reach.
    """
    sources = [args.vol is not None, args.heston, args.quotes is not None]
    if sum(sources) != 1:
        raise SystemExit("give exactly one of --vol, --heston and --quotes")
    if args.time <= 0.0:
        raise SystemExit("--time must be positive")
    if args.forward <= 0.0:
        raise SystemExit("--forward must be positive")
    if args.width <= 0.0:
        raise SystemExit("--width must be positive")
    if args.vol is not None and args.vol <= 0.0:
        raise SystemExit("--vol must be positive")
    if args.step is not None and args.step <= 0.0:
        raise SystemExit("--step must be positive")
    if args.heston:
        for name in ("v0", "kappa", "theta", "sigma", "rho"):
            if getattr(args, name) is None:
                raise SystemExit(f"--heston needs --{name}")
    discount = math.exp(-args.rate * args.time)

    print(f"forward        {args.forward:.6f}")
    print(f"time           {args.time:.6f}")
    print(f"discount       {discount:.10f}")

    model: Heston | None = None
    priced: Callable[[float, OptionType], float] | None = None
    target: float | None = None

    if args.vol is not None:
        flat_vol = args.vol

        def priced_flat(strike: float, option: OptionType) -> float:
            return price(
                Inputs.on_future(args.forward, strike, args.time, args.rate, flat_vol),
                option,
            )

        priced = priced_flat
        target = flat_vol * flat_vol
        print(f"flat vol       {flat_vol:.6%}")
    elif args.heston:
        model = Heston(args.v0, args.kappa, args.theta, args.sigma, args.rho)
        # Zero carry, so the contract's forward is its spot: the replication
        # and the model have to be struck against the same forward or the
        # error against the closed form is dominated by the mismatch rather
        # than by the truncation it is meant to measure.
        spot = args.forward
        heston_model = model

        def priced_heston(strike: float, option: OptionType) -> float:
            return heston_price(
                heston_model, Contract(spot, strike, args.time, args.rate, carry=0.0), option, 1e-13
            )

        priced = priced_heston
        target = model.expected_integrated_variance(args.time) / args.time
        feller = "holds" if model.satisfies_feller else "fails"
        print(f"equivalent vol {model.equivalent_vol(args.time):.6%}")
        print(f"Feller         {feller} (2 kappa theta - sigma^2 = {model.feller:+.6f})")
    print()

    if priced is not None:

        def otm(strike: float) -> float:
            option = OptionType.CALL if strike >= args.forward else OptionType.PUT
            return priced(strike, option)

        replication = fair_variance(
            otm, args.forward, args.time, discount, width=args.width, tol=args.tol
        )
        low_strike = args.forward * math.exp(-args.width)
        high_strike = args.forward * math.exp(args.width)
        print("continuous replication")
        print(f"  strike range   {low_strike:.6g} to {high_strike:.6g}")
        print(f"  fair variance  {replication.fair_variance:.10f}")
        print(f"  in vol terms   {replication.fair_volatility:.6%}")
        print(f"  put wing       {replication.lower:.10f}")
        print(f"  call wing      {replication.upper:.10f}")
        print(f"  outer tenth    {replication.edge:.3e} of the integral")
        if target is not None:
            print(f"  exact answer   {target:.10f}")
            print(f"  relative error {replication.fair_variance / target - 1.0:+.3e}")
        if args.vol is not None:
            predicted = truncation_error(args.forward, args.time, args.vol, low_strike, high_strike)
            print(f"  predicted truncation {predicted:+.3e}")
        print()

    if model is not None:
        swap = volatility_swap_strike(model, args.time)
        print("volatility swap")
        print(f"  root of variance {math.sqrt(swap.variance_strike):.6%}")
        print(f"  second-order     {swap.strike:.6%}")
        print(f"  convexity        {swap.convexity:.6%}")
        print(f"  dispersion       {swap.dispersion:.6f}")
        print("  the second-order term runs a quarter to a half too large")
        print()

    quotes: list[tuple[float, float]] | None = None
    if args.quotes is not None:
        quotes = _read_price_quotes(args.quotes)
    elif args.step is not None:
        if priced is None:  # pragma: no cover - a source is required above
            raise SystemExit("--step needs a model to price the lattice with")
        quotes = _lattice_quotes(priced, args.forward, args.step, args.low, args.high)

    if quotes is not None:
        try:
            strip = Strip.from_quotes(quotes, args.forward, args.time, discount)
        except BadStrip as error:
            raise SystemExit(f"error: {error}") from error
        low, high = strip.log_range
        print(f"listed strip of {len(strip.strikes)} strikes")
        print(f"  log-moneyness  {low:+.4f} to {high:+.4f}")
        print(f"  split strike   {strip.reference:.6f}")
        print(f"  gap to forward {args.forward / strip.reference - 1.0:+.6e}")
        width = max(len(member.value) for member in Centring)
        header = f"  {'centring':>{width}} {'fair variance':>15} {'correction':>13}"
        if target is not None:
            header += f" {'error':>12}"
        print(header)
        for member in Centring:
            result = fair_variance_from_strip(strip, centring=member)
            line = (
                f"  {member.value:>{width}}"
                f" {result.fair_variance:>15.10f}"
                f" {result.correction:>13.3e}"
            )
            if target is not None:
                line += f" {result.fair_variance - target:>+12.3e}"
            print(line)
    return 0


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="moneyness", description="Option pricing, Greeks and implied volatility."
    )
    # Worth having for its own sake, and it doubles as the cheapest possible
    # smoke test of an install: it imports the package and prints something.
    parser.add_argument("--version", action="version", version=f"moneyness {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    price_parser = sub.add_parser("price", help="price one option")
    _add_market(price_parser)
    price_parser.add_argument("--vol", type=float, required=True, help="annualised volatility")
    price_parser.set_defaults(handler=_run_price)

    greeks_parser = sub.add_parser("greeks", help="price and all sensitivities")
    _add_market(greeks_parser)
    greeks_parser.add_argument("--vol", type=float, required=True, help="annualised volatility")
    greeks_parser.set_defaults(handler=_run_greeks)

    iv_parser = sub.add_parser("iv", help="imply volatility from a quoted price")
    _add_market(iv_parser)
    iv_parser.add_argument("--price", type=float, required=True, help="quoted option price")
    iv_parser.add_argument(
        "--brent", action="store_true", help="use Brent rather than safeguarded Newton"
    )
    iv_parser.set_defaults(handler=_run_iv)

    ladder_parser = sub.add_parser("ladder", help="a table of strikes at one maturity")
    ladder_parser.add_argument("--spot", type=float, required=True)
    ladder_parser.add_argument("--time", type=float, required=True)
    ladder_parser.add_argument("--vol", type=float, required=True)
    ladder_parser.add_argument("--rate", type=float, default=0.0)
    ladder_parser.add_argument("--carry", type=float, default=None)
    ladder_parser.add_argument("--dividend", type=float, default=None)
    ladder_parser.add_argument("--future", action="store_true")
    ladder_parser.add_argument("--low", type=float, required=True, help="lowest strike")
    ladder_parser.add_argument("--high", type=float, required=True, help="highest strike")
    ladder_parser.add_argument("--steps", type=int, default=9, help="number of strikes")
    ladder_parser.set_defaults(handler=_run_ladder)

    term_parser = sub.add_parser("term", help="a table of maturities at one strike")
    term_parser.add_argument("--spot", type=float, required=True)
    term_parser.add_argument("--strike", type=float, required=True)
    term_parser.add_argument("--vol", type=float, required=True)
    term_parser.add_argument("--rate", type=float, default=0.0)
    term_parser.add_argument("--carry", type=float, default=None)
    term_parser.add_argument("--dividend", type=float, default=None)
    term_parser.add_argument("--future", action="store_true")
    term_parser.add_argument("--near", type=float, required=True, help="shortest maturity")
    term_parser.add_argument("--far", type=float, required=True, help="longest maturity")
    term_parser.add_argument(
        "--steps", type=int, default=9, help="number of maturities, spaced geometrically"
    )
    term_parser.set_defaults(handler=_run_term)

    surface_parser = sub.add_parser(
        "surface",
        help="fit a volatility surface to quotes and report the arbitrage it admits",
        description=(
            "Reads maturity,strike,vol rows from a CSV file or standard input, fits an "
            "SVI slice per maturity, and reports the fit quality, the butterfly and "
            "calendar conditions, and optionally a grid of local volatilities. Exits 1 "
            "if the fitted surface admits arbitrage."
        ),
    )
    surface_parser.add_argument(
        "--quotes", required=True, help="CSV of maturity,strike,vol, or - for standard input"
    )
    surface_parser.add_argument("--spot", type=float, required=True, help="price of the underlying")
    surface_parser.add_argument("--rate", type=float, default=0.0)
    surface_parser.add_argument(
        "--carry", type=float, default=None, help="cost of carry; defaults to the rate"
    )
    surface_parser.add_argument(
        "--local-vol",
        action="store_true",
        dest="local_vol",
        help="also print a grid of local volatilities",
    )
    surface_parser.add_argument(
        "--reprice",
        action="store_true",
        help=(
            "solve every quote back out of the surface's own local volatility "
            "and report the gap to the quoted volatility"
        ),
    )
    surface_parser.set_defaults(handler=_run_surface)

    american_parser = sub.add_parser(
        "american", help="lattice valuation with the right to exercise early"
    )
    _add_market(american_parser)
    american_parser.add_argument("--vol", type=float, required=True, help="annualised volatility")
    american_parser.add_argument("--steps", type=int, default=512, help="number of lattice layers")
    american_parser.add_argument(
        "--lattice",
        choices=[item.value for item in Lattice],
        default=Lattice.CRR.value,
        help="which lattice construction to build",
    )
    american_parser.add_argument(
        "--raw",
        action="store_true",
        help="disable Broadie-Detemple smoothing, to see the unsmoothed lattice",
    )
    american_parser.add_argument(
        "--boundary", action="store_true", help="also print the early-exercise boundary"
    )
    american_parser.add_argument(
        "--boundary-rows", type=int, default=12, help="how many boundary rows to show"
    )
    american_parser.set_defaults(handler=_run_american)

    heston_parser = sub.add_parser(
        "heston",
        help="a smile generated by stochastic volatility",
        description=(
            "Prices a ladder of strikes under Heston's model and reports the "
            "lognormal volatility that reproduces each price, so the smile the "
            "parameters generate can be read directly."
        ),
    )
    heston_parser.add_argument("--spot", type=float, required=True)
    heston_parser.add_argument("--time", type=float, required=True)
    heston_parser.add_argument("--rate", type=float, default=0.0)
    heston_parser.add_argument("--carry", type=float, default=None)
    heston_parser.add_argument("--dividend", type=float, default=None)
    heston_parser.add_argument("--future", action="store_true")
    heston_parser.add_argument("--v0", type=float, required=True, help="variance now")
    heston_parser.add_argument("--kappa", type=float, required=True, help="reversion speed")
    heston_parser.add_argument("--theta", type=float, required=True, help="long-run variance")
    heston_parser.add_argument("--sigma", type=float, required=True, help="volatility of variance")
    heston_parser.add_argument(
        "--rho", type=float, required=True, help="price/variance correlation"
    )
    heston_parser.add_argument("--low", type=float, required=True, help="lowest strike")
    heston_parser.add_argument("--high", type=float, required=True, help="highest strike")
    heston_parser.add_argument("--steps", type=int, default=9, help="number of strikes")
    heston_parser.add_argument(
        "--check",
        action="store_true",
        help="also report how far the two pricing routes disagree",
    )
    heston_parser.set_defaults(handler=_run_heston)

    sabr_parser = sub.add_parser(
        "sabr",
        help="a SABR smile, and where it stops being a distribution",
        description=(
            "Reports Hagan's lognormal and normal volatilities across a strike "
            "ladder, the price each implies, and the risk-neutral density the "
            "smile carries. The density column is the point: Hagan's formula is "
            "an expansion rather than a price, so nothing makes it convex in the "
            "strike, and --floor finds the highest strike below the forward where "
            "it has turned negative. Short-dated smiles are distributions; long "
            "ones are not, and the boundary can come within a standard deviation "
            "of the forward at ten years."
        ),
    )
    sabr_parser.add_argument("--forward", type=float, required=True)
    sabr_parser.add_argument("--time", type=float, required=True)
    sabr_parser.add_argument("--alpha", type=float, required=True, help="volatility now")
    sabr_parser.add_argument("--beta", type=float, default=0.5, help="backbone exponent, in [0, 1]")
    sabr_parser.add_argument(
        "--rho", type=float, required=True, help="forward/volatility correlation"
    )
    sabr_parser.add_argument("--nu", type=float, required=True, help="volatility of volatility")
    sabr_parser.add_argument("--low", type=float, required=True, help="lowest strike")
    sabr_parser.add_argument("--high", type=float, required=True, help="highest strike")
    sabr_parser.add_argument("--steps", type=int, default=9, help="number of strikes")
    sabr_parser.add_argument(
        "--shift",
        type=float,
        default=None,
        help=(
            "displace the forward and every strike by this much, which is how a "
            "negative-rate market quotes SABR"
        ),
    )
    sabr_parser.add_argument(
        "--floor",
        action="store_true",
        help="also search for where the implied density turns negative",
    )
    sabr_parser.set_defaults(handler=_run_sabr)

    barrier_parser = sub.add_parser(
        "barrier",
        help="a single-barrier option, and where it stops behaving like an option",
        description=(
            "Prices a continuously monitored single-barrier European in closed "
            "form, with its mirror half and the parity residual beside it. Then "
            "two tables. The volatility ladder exists because a knock-out is "
            "the one price in this package that need not rise with volatility: "
            "the volatility that pays for the optionality also pays for the "
            "knock-out, so a barrier near the spot makes the price turn over "
            "and vega change sign. The monitoring table exists because the "
            "shift representing a daily close is under a per cent of the "
            "barrier and worth more than ten per cent of the price."
        ),
    )
    _add_market(barrier_parser)
    barrier_parser.add_argument(
        "--vol", type=float, required=True, help="annualised lognormal volatility"
    )
    barrier_parser.add_argument(
        "--level", type=float, required=True, help="the barrier, as a spot level"
    )
    barrier_parser.add_argument(
        "--barrier",
        choices=[item.value for item in Barrier],
        default=Barrier.UP_AND_OUT.value,
        help="which barrier, and whether it knocks in or out",
    )
    barrier_parser.add_argument(
        "--vols",
        type=float,
        nargs="+",
        default=(0.05, 0.10, 0.15, 0.20, 0.30, 0.40),
        metavar="SIGMA",
        help="volatilities to walk, to show where the price turns over",
    )
    barrier_parser.add_argument(
        "--monitorings",
        type=float,
        nargs="*",
        default=(252.0, 52.0, 12.0),
        metavar="PER_YEAR",
        help="monitoring frequencies to price by the continuity correction",
    )
    barrier_parser.set_defaults(handler=_run_barrier)

    path_parser = sub.add_parser(
        "heston-path",
        help="simulate a payoff under stochastic volatility",
        description=(
            "Simulates Heston's model by Andersen's quadratic-exponential scheme "
            "and prices a European, Asian or barrier payoff from the paths. The "
            "European case reports the gap to the transform price, which is the "
            "check that the simulation is working."
        ),
    )
    _add_market(path_parser)
    path_parser.add_argument("--v0", type=float, required=True, help="variance now")
    path_parser.add_argument("--kappa", type=float, required=True, help="reversion speed")
    path_parser.add_argument("--theta", type=float, required=True, help="long-run variance")
    path_parser.add_argument("--sigma", type=float, required=True, help="volatility of variance")
    path_parser.add_argument("--rho", type=float, required=True, help="price/variance correlation")
    path_parser.add_argument(
        "--payoff", choices=["european", "asian", "barrier"], default="european"
    )
    path_parser.add_argument("--steps", type=int, default=32, help="time steps per path")
    path_parser.add_argument("--paths", type=int, default=20000, help="paths simulated")
    path_parser.add_argument("--seed", type=int, default=0)
    path_parser.add_argument("--level", type=float, default=None, help="the barrier")
    path_parser.add_argument(
        "--barrier",
        choices=[item.value for item in Barrier],
        default=Barrier.DOWN_AND_OUT.value,
    )
    path_parser.add_argument(
        "--no-bridge",
        action="store_true",
        dest="no_bridge",
        help="monitor the barrier only on the grid, with no continuity correction",
    )
    path_parser.add_argument(
        "--no-martingale",
        action="store_true",
        dest="no_martingale",
        help="leave the drift uncorrected, so the simulated forward is only approximate",
    )
    path_parser.set_defaults(handler=_run_heston_path)

    asian_parser = sub.add_parser(
        "asian",
        help="an average-price option, with the interval its price lies in",
        description=(
            "Prices an arithmetic-average option. There is no closed form, so the "
            "report leads with rigorous bounds -- Curran's conditioning bound "
            "below, convexity or AM-GM above -- and shows the moment-matched "
            "price inside them, flagged when it falls outside. Moment matching "
            "breaks the lower bound out of the money at moderate volatility, "
            "which is what the bounds are for."
        ),
    )
    _add_market(asian_parser)
    asian_parser.add_argument(
        "--vol", type=float, required=True, help="annualised lognormal volatility"
    )
    asian_parser.add_argument(
        "--fixings",
        type=int,
        default=12,
        help="equally spaced monitoring dates, the last at expiry",
    )
    asian_parser.add_argument(
        "--fixing-table",
        action="store_true",
        dest="fixing_table",
        help="also show how the bounds tighten as the fixings get dense",
    )
    asian_parser.set_defaults(handler=_run_asian)

    spread_parser = sub.add_parser(
        "spread",
        help="an option on the difference of two assets, with its interval",
        description=(
            "Prices an option on S1 - S2. There is no closed form, so the report "
            "pairs the price with a rigorous interval: a sub-replicating "
            "half-space below, two super-replicating vanillas above. The upper "
            "bound uses no correlation at all, so its distance above the price "
            "measures how far this correlation is from the worst one. Kirk's "
            "approximation is shown inside the interval and flagged when it "
            "leaves it."
        ),
    )
    spread_parser.add_argument("--forward1", type=float, required=True)
    spread_parser.add_argument("--forward2", type=float, required=True)
    spread_parser.add_argument("--strike", type=float, default=0.0)
    spread_parser.add_argument("--time", type=float, required=True)
    spread_parser.add_argument("--rate", type=float, default=0.0)
    spread_parser.add_argument("--vol1", type=float, required=True)
    spread_parser.add_argument("--vol2", type=float, required=True)
    spread_parser.add_argument(
        "--rho", type=float, required=True, help="correlation of the two log returns"
    )
    spread_parser.add_argument(
        "--option", choices=("call", "put"), default="call", help="side of the spread"
    )
    spread_parser.set_defaults(handler=_run_spread)

    variance_parser = sub.add_parser(
        "variance",
        help="the fair strike of a variance swap, by replication",
        description=(
            "Replicates a variance swap from out-of-the-money option prices and "
            "reports what the finite strike range and the lattice spacing cost. "
            "Prices come from a flat volatility, a Heston model or a file of "
            "quotes; the first two have exact answers and the command prints "
            "the error against them."
        ),
    )
    variance_parser.add_argument("--forward", type=float, required=True)
    variance_parser.add_argument("--time", type=float, required=True)
    variance_parser.add_argument("--rate", type=float, default=0.0)
    source = variance_parser.add_argument_group("source of prices (exactly one)")
    source.add_argument("--vol", type=float, default=None, help="a flat lognormal volatility")
    source.add_argument("--heston", action="store_true", help="a Heston smile")
    source.add_argument("--quotes", default=None, help="CSV of strike,price rows, or -")
    model_group = variance_parser.add_argument_group("Heston parameters")
    model_group.add_argument("--v0", type=float, default=None, help="variance now")
    model_group.add_argument("--kappa", type=float, default=None, help="reversion speed")
    model_group.add_argument("--theta", type=float, default=None, help="long-run variance")
    model_group.add_argument("--sigma", type=float, default=None, help="volatility of variance")
    model_group.add_argument("--rho", type=float, default=None, help="correlation")
    variance_parser.add_argument(
        "--width",
        type=float,
        default=3.0,
        help="half-width of the log-moneyness range integrated",
    )
    variance_parser.add_argument(
        "--tol", type=float, default=1e-13, help="absolute tolerance on each wing"
    )
    variance_parser.add_argument(
        "--step", type=float, default=None, help="also sum over a strike lattice of this spacing"
    )
    variance_parser.add_argument(
        "--low", type=float, default=0.1, help="lowest lattice strike, as a multiple of the forward"
    )
    variance_parser.add_argument(
        "--high", type=float, default=10.0, help="highest lattice strike, as a multiple"
    )
    variance_parser.set_defaults(handler=_run_variance)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point. Returns a process exit status."""
    args = _parser().parse_args(argv)
    try:
        result: int = args.handler(args)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return result


if __name__ == "__main__":
    raise SystemExit(main())
