"""Command-line access to the library.

Subcommands: ``price`` for a single option, ``greeks`` for its sensitivities,
``iv`` to invert a quoted price, ``ladder`` for a table of strikes at one
maturity, ``term`` for the transpose of it, ``surface`` to fit a surface to
quotes, ``american`` for a lattice valuation with the right to exercise
early, and ``heston`` for a smile generated by stochastic volatility rather
than fitted to quotes.

The carry is specified in whichever way suits the instrument — ``--carry``
directly, ``--dividend`` for a share, ``--future`` for Black's model — rather
than making the caller do the arithmetic.
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

from . import __version__
from .american import bjerksund_stensland, bjerksund_stensland_2002, trigger_price
from .bsm import Inputs, OptionType, forward, parity_gap, price
from .greeks import (
    charm,
    colour,
    delta,
    dual_delta,
    dual_gamma,
    gamma,
    rho,
    rho_carry,
    speed,
    theta,
    vanna,
    vega,
    veta,
    volga,
    zomma,
)
from .heston import Contract, Heston, gil_pelaez_price, lewis_price, smile
from .heston import price as heston_price
from .heston_mc import asian as heston_asian
from .heston_mc import barrier as heston_barrier
from .heston_mc import european as heston_european
from .implied import Method, Quote, black, bounds, solve
from .lattice import Exercise, Lattice, boundary, min_steps, price_lattice, richardson
from .monte_carlo import Barrier, Settings
from .sabr import (
    SabrParameters,
    bachelier,
    density,
    density_floor,
    lognormal_volatility,
    normal_volatility,
)
from .surface import Surface
from .svi import SVI, Butterfly, calibrate

__all__ = ["main"]


def _carry_from(args: argparse.Namespace) -> float | None:
    """Resolve the cost of carry from whichever flag was given."""
    given = [args.carry is not None, args.dividend is not None, args.future]
    if sum(given) > 1:
        raise SystemExit("give at most one of --carry, --dividend and --future")
    if args.future:
        return 0.0
    if args.dividend is not None:
        return float(args.rate) - float(args.dividend)
    return None if args.carry is None else float(args.carry)


def _add_market(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--spot", type=float, required=True, help="price of the underlying")
    parser.add_argument("--strike", type=float, required=True, help="exercise price")
    parser.add_argument("--time", type=float, required=True, help="year fraction to expiry")
    parser.add_argument("--rate", type=float, default=0.0, help="continuous discount rate")
    carry = parser.add_argument_group("cost of carry (at most one)")
    carry.add_argument("--carry", type=float, default=None, help="cost of carry directly")
    carry.add_argument("--dividend", type=float, default=None, help="continuous dividend yield")
    carry.add_argument(
        "--future", action="store_true", help="option on a future, so the carry is zero"
    )
    parser.add_argument(
        "--put", action="store_true", help="price a put; the default is a call"
    )


def _option_of(args: argparse.Namespace) -> OptionType:
    return OptionType.PUT if args.put else OptionType.CALL


def _inputs_of(args: argparse.Namespace) -> Inputs:
    return Inputs(args.spot, args.strike, args.time, args.rate, args.vol, carry=_carry_from(args))


def _run_price(args: argparse.Namespace) -> int:
    inputs = _inputs_of(args)
    option = _option_of(args)
    print(f"{option.value:>18}  {price(inputs, option):.10f}")
    print(f"{'forward':>18}  {forward(inputs):.10f}")
    print(f"{'discount factor':>18}  {inputs.discount:.10f}")
    print(f"{'parity residual':>18}  {parity_gap(inputs):.3e}")
    return 0


def _run_greeks(args: argparse.Namespace) -> int:
    inputs = _inputs_of(args)
    option = _option_of(args)
    rows: list[tuple[str, float]] = [
        ("price", price(inputs, option)),
        ("delta", delta(inputs, option)),
        ("gamma", gamma(inputs)),
        ("vega", vega(inputs)),
        ("theta", theta(inputs, option)),
        ("rho (rate)", rho(inputs, option)),
        ("rho (carry)", rho_carry(inputs, option)),
        ("vanna", vanna(inputs)),
        ("volga", volga(inputs)),
        ("charm", charm(inputs, option)),
        ("veta", veta(inputs)),
        ("colour", colour(inputs)),
        ("speed", speed(inputs)),
        ("zomma", zomma(inputs)),
        ("dual delta", dual_delta(inputs, option)),
        ("dual gamma", dual_gamma(inputs)),
    ]
    width = max(len(name) for name, _ in rows)
    for name, value in rows:
        print(f"{name:>{width}}  {value:>18.10f}")
    print()
    print("vega is per unit of volatility and theta is per year.")
    return 0


def _run_iv(args: argparse.Namespace) -> int:
    quote = Quote(
        args.spot, args.strike, args.time, args.rate, args.price, carry=_carry_from(args)
    )
    option = _option_of(args)
    limits = bounds(quote, option)
    method = Method.BRENT if args.brent else Method.NEWTON
    try:
        solution = solve(quote, option, method)
    except ValueError as error:
        print(f"could not invert the quote: {error}", file=sys.stderr)
        print(
            f"the price must lie in [{limits.lower:.10f}, {limits.upper:.10f}]",
            file=sys.stderr,
        )
        return 1
    print(f"{'implied volatility':>20}  {solution.vol:.10f}")
    print(f"{'total volatility':>20}  {solution.total_vol:.10f}")
    print(f"{'method':>20}  {solution.method.value}")
    print(f"{'iterations':>20}  {solution.iterations}")
    print(f"{'price residual':>20}  {solution.residual:.3e}")
    print(f"{'arbitrage bounds':>20}  [{limits.lower:.10f}, {limits.upper:.10f}]")
    return 0


def _run_ladder(args: argparse.Namespace) -> int:
    carry = _carry_from(args)
    step = (args.high - args.low) / max(args.steps - 1, 1)
    header = f"{'strike':>10} {'call':>12} {'put':>12} {'delta':>10} {'gamma':>10} {'vega':>12}"
    print(header)
    print("-" * len(header))
    for index in range(args.steps):
        strike = args.low + index * step
        inputs = Inputs(args.spot, strike, args.time, args.rate, args.vol, carry=carry)
        print(
            f"{strike:>10.4f}"
            f" {price(inputs, OptionType.CALL):>12.6f}"
            f" {price(inputs, OptionType.PUT):>12.6f}"
            f" {delta(inputs, OptionType.CALL):>10.6f}"
            f" {gamma(inputs):>10.6f}"
            f" {vega(inputs):>12.6f}"
        )
    return 0


def _run_term(args: argparse.Namespace) -> int:
    """One strike across a range of maturities: the transpose of the ladder.

    The maturities are spaced geometrically rather than evenly. A term
    structure is read in ratios -- a week against a month against a year --
    and an even grid from one week to two years spends almost all of its rows
    on maturities that differ from each other by a rounding error while
    skipping the short end entirely, which is the part that moves.
    """
    carry = _carry_from(args)
    if args.near <= 0.0 or args.far <= 0.0:
        raise SystemExit("--near and --far must both be positive")
    if args.far < args.near:
        raise SystemExit("--far must not be before --near")
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")

    header = (
        f"{'maturity':>10} {'call':>12} {'put':>12} {'delta':>10}"
        f" {'gamma':>10} {'vega':>12} {'theta':>12}"
    )
    print(header)
    print("-" * len(header))

    ratio = 1.0 if args.steps == 1 else (args.far / args.near) ** (1.0 / (args.steps - 1))
    for index in range(args.steps):
        time = args.near * ratio**index
        inputs = Inputs(args.spot, args.strike, time, args.rate, args.vol, carry=carry)
        print(
            f"{time:>10.4f}"
            f" {price(inputs, OptionType.CALL):>12.6f}"
            f" {price(inputs, OptionType.PUT):>12.6f}"
            f" {delta(inputs, OptionType.CALL):>10.6f}"
            f" {gamma(inputs):>10.6f}"
            f" {vega(inputs):>12.6f}"
            f" {theta(inputs, OptionType.CALL):>12.6f}"
        )
    return 0


def _read_quotes(source: str) -> dict[float, list[tuple[float, float]]]:
    """Read ``maturity,strike,vol`` rows, grouped by maturity.

    A header row is optional and detected by trying to parse it as numbers,
    which is more forgiving than demanding a particular spelling and less
    fragile than guessing from the text. It is allowed to follow comment lines
    rather than having to be the very first line, since a file that explains
    where its quotes came from is more useful than one that does not.

    Args:
        source: Path to a CSV, or ``-`` for standard input.

    Returns:
        Quotes grouped by maturity, in file order within each group.

    Raises:
        SystemExit: If the file cannot be read, a row is malformed, or a value
            is outside its domain. The row number is always reported, because a
            surface is typically a few hundred rows and "one of them is wrong"
            is not a usable diagnostic.
    """
    if source == "-":
        lines: Iterable[str] = sys.stdin.read().splitlines()
    else:
        path = Path(source)
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError as error:
            raise SystemExit(f"cannot read {source}: {error}") from error

    grouped: dict[float, list[tuple[float, float]]] = {}
    for number, row in enumerate(csv.reader(lines), start=1):
        cleaned = [field.strip() for field in row if field.strip()]
        if not cleaned or cleaned[0].startswith("#"):
            continue
        if len(cleaned) < 3:
            raise SystemExit(
                f"row {number}: expected maturity, strike and vol, got {len(cleaned)} fields"
            )
        try:
            maturity, strike, vol = (float(field) for field in cleaned[:3])
        except ValueError:
            if not grouped:
                continue  # a header, wherever it happens to sit
            raise SystemExit(f"row {number}: {cleaned[:3]} are not three numbers") from None
        if maturity <= 0.0:
            raise SystemExit(f"row {number}: maturity {maturity} is not positive")
        if strike <= 0.0:
            raise SystemExit(f"row {number}: strike {strike} is not positive")
        if vol <= 0.0:
            raise SystemExit(f"row {number}: volatility {vol} is not positive")
        grouped.setdefault(maturity, []).append((strike, vol))

    if not grouped:
        raise SystemExit(f"no quotes found in {source}")
    return grouped


def _run_surface(args: argparse.Namespace) -> int:
    """Fit a surface to quoted volatilities and report what it implies.

    Returns 1 when the fitted surface admits arbitrage, so that the command is
    usable as a check in a pipeline. That is a finding about the data rather
    than a failure of the request, which is why it is an exit status and not an
    exception.
    """
    grouped = _read_quotes(args.quotes)
    carry = args.rate if args.carry is None else args.carry

    fitted: list[tuple[float, SVI]] = []
    print(f"{'maturity':>9} {'quotes':>7} {'rmse':>11} {'max err':>11}"
          f" {'a':>9} {'b':>8} {'rho':>8} {'m':>8} {'s':>8}"
          f" {'left':>7} {'right':>7} {'worst g':>10}")
    print("-" * 120)

    arbitrage = False
    for maturity in sorted(grouped):
        quotes = grouped[maturity]
        if len(quotes) < 5:
            raise SystemExit(
                f"maturity {maturity} has {len(quotes)} quotes; "
                "a five-parameter slice needs at least five"
            )
        forward_price = args.spot * math.exp(carry * maturity)
        log_moneyness = [math.log(strike / forward_price) for strike, _ in quotes]
        variance = [vol * vol * maturity for _, vol in quotes]

        try:
            fit = calibrate(log_moneyness, variance)
        except ValueError as error:
            raise SystemExit(f"maturity {maturity}: {error}") from error

        slice_ = fit.slice_
        left, right = slice_.wing_slopes
        report = Butterfly.scan(slice_)
        if not report.free:
            arbitrage = True
        print(
            f"{maturity:>9.4f} {len(quotes):>7d} {fit.rmse:>11.3e} {fit.max_error:>11.3e}"
            f" {slice_.a:>9.5f} {slice_.b:>8.5f} {slice_.rho:>8.5f}"
            f" {slice_.m:>8.5f} {slice_.s:>8.5f}"
            f" {left:>7.3f} {right:>7.3f} {report.worst:>10.5f}"
        )
        fitted.append((maturity, slice_))

    surface = Surface(fitted)

    print()
    print("butterfly (worst value of Durrleman's function; negative implies a negative density)")
    for maturity, worst, at in surface.butterfly():
        quoted = "quoted" if maturity in grouped else "interpolated"
        flag = "  ARBITRAGE" if worst < 0.0 else ""
        if worst < 0.0:
            arbitrage = True
        print(f"  T={maturity:<9.4f} {quoted:<13} g={worst:>10.5f} at k={at:>7.3f}{flag}")

    print()
    if len(fitted) < 2:
        print("calendar: a single maturity cannot cross another")
    else:
        print("calendar (total variance must not fall as maturity grows)")
        for entry in surface.calendar():
            if entry.free:
                margin = -entry.worst
                print(
                    f"  {entry.earlier:.4f} -> {entry.later:.4f}  clear,"
                    f" closest approach {margin:.5f}"
                )
            else:
                arbitrage = True
                print(
                    f"  {entry.earlier:.4f} -> {entry.later:.4f}  CROSSES by"
                    f" {entry.worst:.5f} at k={entry.at:.3f}"
                )

    if args.local_vol:
        print()
        print("local volatility by the Dupire identity")
        maturities = surface.maturities
        if len(maturities) < 2:
            print("  a single maturity gives no slope in maturity, so dw/dT is zero")
            print("  everywhere and the identity has nothing to report")
            print()
            if arbitrage:
                print("verdict: the fitted surface admits arbitrage")
                return 1
            print("verdict: no arbitrage found")
            return 0

        # Strictly inside the quoted range. At a quoted endpoint the surface is
        # flat in maturity by construction -- that is what the extrapolation
        # rule says -- so dw/dT is zero there and the identity returns a local
        # volatility of zero. That number is a property of the extrapolation,
        # not of the market, and printing it in a column headed by a real
        # maturity would invite it to be read as one.
        near, far = maturities[0], maturities[-1]
        columns = 5
        times = [near + (far - near) * (i + 1) / (columns + 1) for i in range(columns)]
        header = f"{'k':>8}" + "".join(f"{t:>12.4f}" for t in times)
        print(header)
        print("-" * len(header))
        for step in range(-4, 5):
            k = step * 0.1
            cells = []
            for time in times:
                result = surface.local_vol(k, time)
                cells.append(
                    f"{result.volatility:>12.6f}" if result.admissible else f"{'--':>12}"
                )
            print(f"{k:>8.2f}" + "".join(cells))

    print()
    if arbitrage:
        print("verdict: the fitted surface admits arbitrage")
        return 1
    print("verdict: no arbitrage found")
    return 0


def _format_trigger(level: float) -> str:
    """An unreachable boundary is reported as such rather than as a number."""
    return "never reached" if math.isinf(level) else f"{level:.10f}"


def _run_american(args: argparse.Namespace) -> int:
    inputs = _inputs_of(args)
    option = _option_of(args)
    lattice = Lattice(args.lattice)

    floor = min_steps(inputs, lattice)
    if args.steps < floor:
        print(
            f"error: {args.steps} layers is below the {floor} this lattice needs "
            f"for the drift to stay inside the spread",
            file=sys.stderr,
        )
        return 1

    american = price_lattice(
        inputs, option, steps=args.steps, lattice=lattice, smooth=not args.raw
    )
    european = price_lattice(
        inputs,
        option,
        steps=args.steps,
        lattice=lattice,
        exercise=Exercise.EUROPEAN,
        smooth=not args.raw,
    )
    extrapolated = richardson(
        inputs, option, steps=args.steps, lattice=lattice, smooth=not args.raw
    )

    rows: list[tuple[str, str]] = [
        ("lattice", lattice.value),
        ("layers", str(args.steps)),
        ("smoothing", "off" if args.raw else "on"),
        ("american", f"{american.value:.10f}"),
        ("european (lattice)", f"{european.value:.10f}"),
        ("european (closed form)", f"{price(inputs, option):.10f}"),
        ("early exercise premium", f"{american.early_exercise_premium:.10f}"),
        ("american (extrapolated)", f"{extrapolated:.10f}"),
        ("bjerksund-stensland 1993", f"{bjerksund_stensland(inputs, option):.10f}"),
        ("bjerksund-stensland 2002", f"{bjerksund_stensland_2002(inputs, option):.10f}"),
        ("bs trigger price", _format_trigger(trigger_price(inputs, option))),
    ]
    width = max(len(name) for name, _ in rows)
    for name, value in rows:
        print(f"{name:>{width}}  {value}")

    if args.boundary:
        curve = boundary(inputs, option, steps=args.steps, lattice=lattice)
        print()
        if len(curve) <= 1:
            print("the exercise region is empty: early exercise is never optimal here.")
            return 0
        print(f"{'time':>10} {'critical spot':>16}")
        print("-" * 27)
        shown = curve[:: max(len(curve) // args.boundary_rows, 1)]
        if shown[-1] != curve[-1]:
            shown.append(curve[-1])
        for when, critical in shown:
            print(f"{when:>10.6f} {critical:>16.6f}")
    return 0


def _run_sabr(args: argparse.Namespace) -> int:
    """A SABR ladder, both volatility conventions, and the density.

    The two volatility columns are not conversions of one another: they are
    separate second-order expansions in the same small parameter, so the prices
    they imply differ by the expansion's own error -- which the price columns
    make visible rather than hiding behind a single number.
    """
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")
    if args.high < args.low:
        raise SystemExit("--high must not be below --low")
    try:
        parameters = SabrParameters(
            alpha=args.alpha, beta=args.beta, rho=args.rho, nu=args.nu
        )
    except ValueError as bad:
        raise SystemExit(str(bad)) from bad

    shift = args.shift
    fwd = args.forward + shift if shift is not None else args.forward
    if fwd <= 0.0:
        raise SystemExit(
            f"the forward is {fwd}, which the lognormal formula has no value "
            "at; pass --shift to displace it"
        )
    root = math.sqrt(args.time)
    step = (args.high - args.low) / max(args.steps - 1, 1)
    strikes = [args.low + index * step for index in range(args.steps)]

    at_the_money = normal_volatility(parameters, fwd, fwd, args.time) * root
    print(f"forward            {fwd:.6f}" + (f" (shifted by {shift})" if shift else ""))
    print(f"at-the-money sd    {at_the_money:.8f}")
    print(f"backbone exponent  {parameters.beta}")
    if parameters.is_lognormal:
        print("this is Black exactly: no vol of vol and a unit exponent")
    if parameters.is_normal:
        print("this is Bachelier exactly: no vol of vol and a zero exponent")
    print()
    header = (
        f"{'strike':>10} {'lognormal':>12} {'normal':>12} {'black':>14} "
        f"{'bachelier':>14} {'density':>12}"
    )
    print(header)
    print("-" * len(header))
    for strike in strikes:
        shifted = strike + shift if shift is not None else strike
        if shifted <= 0.0:
            print(f"{strike:>10.6f}   (strike not positive after the shift)")
            continue
        lognormal = lognormal_volatility(parameters, fwd, shifted, args.time)
        normal = normal_volatility(parameters, fwd, shifted, args.time)
        option = OptionType.PUT if shifted < fwd else OptionType.CALL
        from_black = black(fwd, shifted, lognormal * root, option)
        from_normal = bachelier(fwd, shifted, normal * root, option)
        here = density(parameters, fwd, shifted, args.time)
        print(
            f"{strike:>10.6f} {lognormal:>12.6%} {normal:>12.8f} "
            f"{from_black:>14.10f} {from_normal:>14.10f} {here:>12.4f}"
        )
    if args.floor:
        print()
        found = density_floor(parameters, fwd, args.time, lower=1e-4 * fwd)
        if found is None:
            print(
                "the density stays non-negative down to 1e-04 of the forward, which "
                "is a search that found nothing rather than a certificate"
            )
        else:
            deviations = (fwd - found) / at_the_money
            inside = density(parameters, fwd, 0.9 * found, args.time, step=1e-4 * found)
            print(
                f"the density turns negative below {found:.6f}, which is "
                f"{deviations:.2f} at-the-money standard deviations below the "
                f"forward; ten per cent further down it is {inside:.4f}"
            )
            print(
                "the value at the boundary itself is a bisected zero and is "
                "rounding, so the magnitude is read inside the region"
            )
    return 0


def _run_heston(args: argparse.Namespace) -> int:
    """A strike ladder under stochastic volatility, read back as a smile.

    The implied volatility column is the point of the command. Prices under a
    model with random variance are not comparable across strikes by eye;
    the volatilities that reproduce them are, and the shape they trace is the
    thing the parameters were chosen for.
    """
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")
    if args.low <= 0.0 or args.high < args.low:
        raise SystemExit("--low must be positive and --high must not be below it")

    model = Heston(args.v0, args.kappa, args.theta, args.sigma, args.rho)
    contract = Contract(args.spot, args.spot, args.time, args.rate, carry=_carry_from(args))
    step = (args.high - args.low) / max(args.steps - 1, 1)
    strikes = [args.low + index * step for index in range(args.steps)]

    feller = "holds" if model.satisfies_feller else "fails"
    print(f"forward           {contract.forward:.6f}")
    print(f"expected variance {model.expected_integrated_variance(args.time):.8f}")
    print(f"equivalent vol    {model.equivalent_vol(args.time):.6%}")
    print(f"Feller condition  {feller} (2 kappa theta - sigma^2 = {model.feller:+.6f})")
    print()

    header = f"{'strike':>10} {'side':>5} {'price':>14} {'implied vol':>13} {'log-moneyness':>15}"
    print(header)
    print("-" * len(header))
    for point in smile(model, contract, strikes):
        vol = "-" if point.implied_vol is None else f"{point.implied_vol:>12.6%}"
        print(
            f"{point.strike:>10.4f}"
            f" {point.option.value:>5}"
            f" {point.price:>14.8f}"
            f" {vol:>13}"
            f" {math.log(point.strike / contract.forward):>15.6f}"
        )

    if args.check:
        # The second route, for a caller who wants the agreement in front of
        # them rather than in the test suite.
        worst = 0.0
        for strike in strikes:
            one = Contract(args.spot, strike, args.time, args.rate, carry=_carry_from(args))
            option = OptionType.CALL if strike >= contract.forward else OptionType.PUT
            gap = lewis_price(model, one, option) - gil_pelaez_price(model, one, option)
            worst = max(worst, abs(gap))
        print()
        print(f"largest gap between the Lewis and Gil-Pelaez routes: {worst:.3e}")
    return 0


def _run_heston_path(args: argparse.Namespace) -> int:
    """A payoff the transform cannot reach, simulated under stochastic volatility.

    The European case is included on purpose even though the transform prices
    it exactly: it is the only payoff here with a known answer, so it is the
    one that says whether the simulation is working before the other two are
    believed.
    """
    if args.steps < 1:
        raise SystemExit("--steps must be at least 1")
    model = Heston(args.v0, args.kappa, args.theta, args.sigma, args.rho)
    contract = Contract(
        args.spot, args.strike, args.time, args.rate, carry=_carry_from(args)
    )
    option = _option_of(args)
    settings = Settings(
        paths=args.paths, seed=args.seed, antithetic=True, control=True
    )

    if args.payoff == "european":
        estimate = heston_european(
            model, contract, option, args.steps, settings, not args.no_martingale
        )
    elif args.payoff == "asian":
        estimate = heston_asian(
            model, contract, option, args.steps, settings, not args.no_martingale
        )
    else:
        if args.level is None:
            raise SystemExit("--level is required for a barrier payoff")
        estimate = heston_barrier(
            model,
            contract,
            option,
            Barrier(args.barrier),
            args.level,
            args.steps,
            settings,
            not args.no_martingale,
            not args.no_bridge,
        )

    low, high = estimate.interval(0.95)
    print(f"payoff            {args.payoff} {option.value}")
    print(f"forward           {contract.forward:.6f}")
    print(f"Feller condition  {'holds' if model.satisfies_feller else 'fails'}")
    print(f"paths             {estimate.paths} in {estimate.samples} samples")
    print(f"steps             {args.steps}")
    print(f"control           {estimate.control or 'none'}")
    print(f"value             {estimate.value:.6f}")
    print(f"standard error    {estimate.standard_error:.6f}")
    print(f"95% interval      [{low:.6f}, {high:.6f}]")
    if args.payoff == "european":
        exact = heston_price(model, contract, option)
        deviations = (estimate.value - exact) / estimate.standard_error
        print(f"transform price   {exact:.6f}")
        gap = estimate.value - exact
        print(f"gap               {gap:+.6f} ({deviations:+.2f} standard errors)")
    return 0


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="moneyness", description="Option pricing, Greeks and implied volatility."
    )
    # Worth having for its own sake, and it doubles as the cheapest possible
    # smoke test of an install: it imports the package and prints something.
    parser.add_argument("--version", action="version", version=f"moneyness {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    price_parser = sub.add_parser("price", help="price one option")
    _add_market(price_parser)
    price_parser.add_argument("--vol", type=float, required=True, help="annualised volatility")
    price_parser.set_defaults(handler=_run_price)

    greeks_parser = sub.add_parser("greeks", help="price and all sensitivities")
    _add_market(greeks_parser)
    greeks_parser.add_argument("--vol", type=float, required=True, help="annualised volatility")
    greeks_parser.set_defaults(handler=_run_greeks)

    iv_parser = sub.add_parser("iv", help="imply volatility from a quoted price")
    _add_market(iv_parser)
    iv_parser.add_argument("--price", type=float, required=True, help="quoted option price")
    iv_parser.add_argument(
        "--brent", action="store_true", help="use Brent rather than safeguarded Newton"
    )
    iv_parser.set_defaults(handler=_run_iv)

    ladder_parser = sub.add_parser("ladder", help="a table of strikes at one maturity")
    ladder_parser.add_argument("--spot", type=float, required=True)
    ladder_parser.add_argument("--time", type=float, required=True)
    ladder_parser.add_argument("--vol", type=float, required=True)
    ladder_parser.add_argument("--rate", type=float, default=0.0)
    ladder_parser.add_argument("--carry", type=float, default=None)
    ladder_parser.add_argument("--dividend", type=float, default=None)
    ladder_parser.add_argument("--future", action="store_true")
    ladder_parser.add_argument("--low", type=float, required=True, help="lowest strike")
    ladder_parser.add_argument("--high", type=float, required=True, help="highest strike")
    ladder_parser.add_argument("--steps", type=int, default=9, help="number of strikes")
    ladder_parser.set_defaults(handler=_run_ladder)

    term_parser = sub.add_parser(
        "term", help="a table of maturities at one strike"
    )
    term_parser.add_argument("--spot", type=float, required=True)
    term_parser.add_argument("--strike", type=float, required=True)
    term_parser.add_argument("--vol", type=float, required=True)
    term_parser.add_argument("--rate", type=float, default=0.0)
    term_parser.add_argument("--carry", type=float, default=None)
    term_parser.add_argument("--dividend", type=float, default=None)
    term_parser.add_argument("--future", action="store_true")
    term_parser.add_argument("--near", type=float, required=True, help="shortest maturity")
    term_parser.add_argument("--far", type=float, required=True, help="longest maturity")
    term_parser.add_argument(
        "--steps", type=int, default=9, help="number of maturities, spaced geometrically"
    )
    term_parser.set_defaults(handler=_run_term)

    surface_parser = sub.add_parser(
        "surface",
        help="fit a volatility surface to quotes and report the arbitrage it admits",
        description=(
            "Reads maturity,strike,vol rows from a CSV file or standard input, fits an "
            "SVI slice per maturity, and reports the fit quality, the butterfly and "
            "calendar conditions, and optionally a grid of local volatilities. Exits 1 "
            "if the fitted surface admits arbitrage."
        ),
    )
    surface_parser.add_argument(
        "--quotes", required=True, help="CSV of maturity,strike,vol, or - for standard input"
    )
    surface_parser.add_argument(
        "--spot", type=float, required=True, help="price of the underlying"
    )
    surface_parser.add_argument("--rate", type=float, default=0.0)
    surface_parser.add_argument(
        "--carry", type=float, default=None, help="cost of carry; defaults to the rate"
    )
    surface_parser.add_argument(
        "--local-vol",
        action="store_true",
        dest="local_vol",
        help="also print a grid of local volatilities",
    )
    surface_parser.set_defaults(handler=_run_surface)

    american_parser = sub.add_parser(
        "american", help="lattice valuation with the right to exercise early"
    )
    _add_market(american_parser)
    american_parser.add_argument(
        "--vol", type=float, required=True, help="annualised volatility"
    )
    american_parser.add_argument(
        "--steps", type=int, default=512, help="number of lattice layers"
    )
    american_parser.add_argument(
        "--lattice",
        choices=[item.value for item in Lattice],
        default=Lattice.CRR.value,
        help="which lattice construction to build",
    )
    american_parser.add_argument(
        "--raw",
        action="store_true",
        help="disable Broadie-Detemple smoothing, to see the unsmoothed lattice",
    )
    american_parser.add_argument(
        "--boundary", action="store_true", help="also print the early-exercise boundary"
    )
    american_parser.add_argument(
        "--boundary-rows", type=int, default=12, help="how many boundary rows to show"
    )
    american_parser.set_defaults(handler=_run_american)

    heston_parser = sub.add_parser(
        "heston",
        help="a smile generated by stochastic volatility",
        description=(
            "Prices a ladder of strikes under Heston's model and reports the "
            "lognormal volatility that reproduces each price, so the smile the "
            "parameters generate can be read directly."
        ),
    )
    heston_parser.add_argument("--spot", type=float, required=True)
    heston_parser.add_argument("--time", type=float, required=True)
    heston_parser.add_argument("--rate", type=float, default=0.0)
    heston_parser.add_argument("--carry", type=float, default=None)
    heston_parser.add_argument("--dividend", type=float, default=None)
    heston_parser.add_argument("--future", action="store_true")
    heston_parser.add_argument("--v0", type=float, required=True, help="variance now")
    heston_parser.add_argument("--kappa", type=float, required=True, help="reversion speed")
    heston_parser.add_argument("--theta", type=float, required=True, help="long-run variance")
    heston_parser.add_argument(
        "--sigma", type=float, required=True, help="volatility of variance"
    )
    heston_parser.add_argument(
        "--rho", type=float, required=True, help="price/variance correlation"
    )
    heston_parser.add_argument("--low", type=float, required=True, help="lowest strike")
    heston_parser.add_argument("--high", type=float, required=True, help="highest strike")
    heston_parser.add_argument("--steps", type=int, default=9, help="number of strikes")
    heston_parser.add_argument(
        "--check",
        action="store_true",
        help="also report how far the two pricing routes disagree",
    )
    heston_parser.set_defaults(handler=_run_heston)

    sabr_parser = sub.add_parser(
        "sabr",
        help="a SABR smile, and where it stops being a distribution",
        description=(
            "Reports Hagan's lognormal and normal volatilities across a strike "
            "ladder, the price each implies, and the risk-neutral density the "
            "smile carries. The density column is the point: Hagan's formula is "
            "an expansion rather than a price, so nothing makes it convex in the "
            "strike, and --floor finds the highest strike below the forward where "
            "it has turned negative. Short-dated smiles are distributions; long "
            "ones are not, and the boundary can come within a standard deviation "
            "of the forward at ten years."
        ),
    )
    sabr_parser.add_argument("--forward", type=float, required=True)
    sabr_parser.add_argument("--time", type=float, required=True)
    sabr_parser.add_argument("--alpha", type=float, required=True, help="volatility now")
    sabr_parser.add_argument(
        "--beta", type=float, default=0.5, help="backbone exponent, in [0, 1]"
    )
    sabr_parser.add_argument(
        "--rho", type=float, required=True, help="forward/volatility correlation"
    )
    sabr_parser.add_argument(
        "--nu", type=float, required=True, help="volatility of volatility"
    )
    sabr_parser.add_argument("--low", type=float, required=True, help="lowest strike")
    sabr_parser.add_argument("--high", type=float, required=True, help="highest strike")
    sabr_parser.add_argument("--steps", type=int, default=9, help="number of strikes")
    sabr_parser.add_argument(
        "--shift",
        type=float,
        default=None,
        help=(
            "displace the forward and every strike by this much, which is how a "
            "negative-rate market quotes SABR"
        ),
    )
    sabr_parser.add_argument(
        "--floor",
        action="store_true",
        help="also search for where the implied density turns negative",
    )
    sabr_parser.set_defaults(handler=_run_sabr)

    path_parser = sub.add_parser(
        "heston-path",
        help="simulate a payoff under stochastic volatility",
        description=(
            "Simulates Heston's model by Andersen's quadratic-exponential scheme "
            "and prices a European, Asian or barrier payoff from the paths. The "
            "European case reports the gap to the transform price, which is the "
            "check that the simulation is working."
        ),
    )
    _add_market(path_parser)
    path_parser.add_argument("--v0", type=float, required=True, help="variance now")
    path_parser.add_argument("--kappa", type=float, required=True, help="reversion speed")
    path_parser.add_argument("--theta", type=float, required=True, help="long-run variance")
    path_parser.add_argument("--sigma", type=float, required=True, help="volatility of variance")
    path_parser.add_argument("--rho", type=float, required=True, help="price/variance correlation")
    path_parser.add_argument(
        "--payoff", choices=["european", "asian", "barrier"], default="european"
    )
    path_parser.add_argument("--steps", type=int, default=32, help="time steps per path")
    path_parser.add_argument("--paths", type=int, default=20000, help="paths simulated")
    path_parser.add_argument("--seed", type=int, default=0)
    path_parser.add_argument("--level", type=float, default=None, help="the barrier")
    path_parser.add_argument(
        "--barrier",
        choices=[item.value for item in Barrier],
        default=Barrier.DOWN_AND_OUT.value,
    )
    path_parser.add_argument(
        "--no-bridge",
        action="store_true",
        dest="no_bridge",
        help="monitor the barrier only on the grid, with no continuity correction",
    )
    path_parser.add_argument(
        "--no-martingale",
        action="store_true",
        dest="no_martingale",
        help="leave the drift uncorrected, so the simulated forward is only approximate",
    )
    path_parser.set_defaults(handler=_run_heston_path)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point. Returns a process exit status."""
    args = _parser().parse_args(argv)
    try:
        result: int = args.handler(args)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return result


if __name__ == "__main__":
    raise SystemExit(main())
